### PR TITLE
Post: Rust Build System

### PR DESCRIPTION
**Pull request by ysndr**
@arxra

### CODE REVIEW

**Comment by ysndr** [comment]
Preview available under https://ysndr.de/beta/18/posts/essays/2021-04-30-the-rust-build-system

**Comment by arxra** [comment]
Very nice! Impressed by how well the render came out! 😄

**Comment by ysndr** [comment]
Glad you like it. Are you happy with the subtitle, I feel its a bit boring so far

**Comment by arxra** [comment]
yeah, the blog-intro makes sense, no complaints from me!
Not sure how you can make "CI/CD" less boring though, think either you'll find the article interesting or not 😰

**Comment by ysndr** [comment]
Sure, I was talking about the "A tale in two repositories" part in the title

**Pull request merged**
